name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install NPM Dependencies
        run: pnpm i

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install composer Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Test
        run: pnpm test

      - name: Check Types
        run: pnpm check-types
